#version: '3'

networks:
  app-tasklist-network:
    driver: bridge

volumes:
  cache:
    driver: local
  db-data:
    driver: local
  minio-data:
    driver: local
  smtp4dev-data:
    driver: local

services:
  app-tasklist:
    image: registry.stx/tasklist:0.0.1
    container_name: app-tasklist
    networks:
      - app-tasklist-network
    depends_on:
      - app-tasklist-db
      - app-tasklist-minio
      - app-tasklist-redis
      - app-tasklist-smtp4dev
    env_file:
      - .env
    ports:
      - '${TASKLIST_PORT}:8086'

  app-tasklist-db:
    image: postgres:17-alpine3.22
    container_name: app-tasklist-db
    networks:
      - app-tasklist-network
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes:
      - ./src/main/resources/db-init:/docker-entrypoint-initdb.d
      - db-data:/var/lib/postgresql/data

  app-tasklist-pgadmin:
    container_name: app-tasklist-pgadmin
    image: dpage/pgadmin4:9.8.0
    networks:
      - app-tasklist-network
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - '${PGADMIN_PORT}:80'
    depends_on:
      - app-tasklist-db

  app-tasklist-redis:
    image: redis:8.2.1-alpine
    restart: always
    container_name: app-tasklist-redis
    networks:
      - app-tasklist-network
    ports:
      - '${REDIS_PORT}:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    volumes:
      - cache:/data

  app-tasklist-minio:
    image: minio/minio:latest
    container_name: app-tasklist-minio
    networks:
      - app-tasklist-network
    environment:
      - MINIO_ROOT_USER=${MINIO_ACCESS_KEY}
      - MINIO_ROOT_PASSWORD=${MINIO_SECRET_KEY}
    command: server ~/minio --console-address :9090
    ports:
      - '9099:9090'
      - '9009:9000'
    volumes:
      - minio-data:/minio

  app-tasklist-smtp4dev:
    image: rnwood/smtp4dev:linux-amd64-prerelease
    container_name: app-tasklist-smtp4dev
    ports:
      - '127.0.0.1:5000:80'    # Web interface
      - '127.0.0.1:2525:25'    # SMTP server (using non-standard port)
      - '127.0.0.1:1143:143'   # IMAP server (using non-standard port)
    volumes:
      - smtp4dev-data:/smtp4dev